---
deployment:
    tasks:
            - export DEPLOYPATH=/home/devorwye/public_html/
            - /bin/cp -R /home/devorwye/devol.me/_website/index.html /home/public_html/ $DEPLOYPATH
            - /bin/cp -R /home/devorwye/devol.me/_website/ /home/devorwye/public_html/ $DEPLOYPATH
            - /bin/cp -R /home/devorwye/devol.me/_website/_images/ /home/devorwye/public_html/_images

---
